# Generated by Django 3.1.7 on 2021-03-30 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210329_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgchannel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tgchannel',
            name='observing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tgchannel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
