# Generated by Django 3.1.7 on 2021-03-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210330_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgchannel',
            name='channel_id',
            field=models.BigIntegerField(),
        ),
    ]
