# Generated by Django 3.1.7 on 2021-03-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210330_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgchannel',
            name='peer_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tgchannel',
            name='real_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
