# Generated by Django 3.1.7 on 2021-03-30 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210330_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgchannel',
            name='peer_type',
        ),
    ]
